# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.8.8.dev124+g1a205da7.d20220903'
__version_tuple__ = version_tuple = (1, 8, 8, 'dev124', 'g1a205da7.d20220903')
